package Interfaces;

import Controladores.ConexionBD;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Equipo
 */
public class jfrmVerMatriculas extends javax.swing.JFrame {

    /**
     * Creates new form jfrmVerMatriculas
     */
    public jfrmVerMatriculas() {
        initComponents();
        setLocationRelativeTo(null); 
        setResizable(false);
        mostrarTodo("");

    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableMatriculasAll = new javax.swing.JTable();
        lblTotalRegistros = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtBusquedaGlobal = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(125, 168, 182));

        jPanel3.setBackground(new java.awt.Color(125, 168, 182));

        jtableMatriculasAll.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtableMatriculasAll);

        lblTotalRegistros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Filtrar:");

        jtxtBusquedaGlobal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBusquedaGlobalActionPerformed(evt);
            }
        });
        jtxtBusquedaGlobal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtBusquedaGlobalKeyReleased(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(92, 146, 164));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/enter.png"))); // NOI18N
        btnSalir.setText("REGRESAR");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(38, 39, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MATRICULAS");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 973, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtBusquedaGlobal, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(213, 213, 213)
                        .addComponent(lblTotalRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTotalRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalir)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtBusquedaGlobal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtBusquedaGlobalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBusquedaGlobalActionPerformed
        
    }//GEN-LAST:event_jtxtBusquedaGlobalActionPerformed

    private void jtxtBusquedaGlobalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBusquedaGlobalKeyReleased
       mostrarTodo(jtxtBusquedaGlobal.getText());
    }//GEN-LAST:event_jtxtBusquedaGlobalKeyReleased

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        btnSalir.setBackground(new Color(136,176,189));
        btnSalir.setForeground(Color.red);
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        btnSalir.setBackground(new Color(92,146,164));
        btnSalir.setForeground(Color.black);
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed
    public void mostrarTodo(String Valor){
        String sql = Valor.isEmpty()
            ? "SELECT m.num_matricula, m.periodo, m.mes_inicio, m.fecha, m.turno, m.cod_alumno, " +
            "CONCAT(a.nombre, ' ', a.apellido) AS nombre_alumno, " +
            "c.curso, c.tipo, " +
            "CONCAT(e.nombre, ' ', e.apellido) AS nombre_empleado " +
            "FROM tb_matricula m " +
            "INNER JOIN tb_alumno a ON m.cod_alumno = a.cod_alumno " +
            "INNER JOIN tb_curso c ON m.cod_curso = c.cod_curso " +
            "INNER JOIN tb_empleado e ON m.cod_emp = e.cod_emp " +
            "LEFT JOIN tb_nota n ON m.num_matricula = n.num_matricula " +
            "ORDER BY m.num_matricula ASC"
            : "SELECT m.num_matricula, m.periodo, m.mes_inicio, m.fecha, m.turno, m.cod_alumno, " +
            "CONCAT(a.nombre, ' ', a.apellido), " +
            "c.curso, c.tipo, " +
            "CONCAT(e.nombre, ' ', e.apellido) AS nombre_empleado " +
            "FROM tb_matricula m " +
            "INNER JOIN tb_alumno a ON m.cod_alumno = a.cod_alumno " +
            "INNER JOIN tb_curso c ON m.cod_curso = c.cod_curso " +
            "INNER JOIN tb_empleado e ON m.cod_emp = e.cod_emp " +
            "LEFT JOIN tb_nota n ON m.num_matricula = n.num_matricula " +
            "WHERE m.num_matricula LIKE '%" + Valor + "%' OR " +
            "m.mes_inicio LIKE '%" + Valor + "%' OR " +
            "m.periodo LIKE '%" + Valor + "%' OR " +
            "m.cod_alumno LIKE '%" + Valor + "%' OR " +
            "CONCAT(a.nombre, ' ', a.apellido) LIKE '%" + Valor + "%' OR " +
            "CONCAT(e.nombre, ' ', e.apellido) LIKE '%" + Valor + "%' OR " +
            "m.fecha LIKE '%" + Valor + "%' OR " +
            "m.turno LIKE '%" + Valor + "%' OR " +
            "c.curso LIKE '%" + Valor + "%' OR " +
            "m.cod_curso LIKE '%" + Valor + "%' OR " +
            "m.cod_emp LIKE '%" + Valor + "%'";

        try (Connection conn = ConexionBD.conectarBD();PreparedStatement pst = conn.prepareStatement(sql, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
               ResultSet rs = pst.executeQuery()) {

            // Obtener la cantidad total de filas en el ResultSet
            rs.last();
            int rowCount = rs.getRow();
            rs.beforeFirst();

            DefaultTableModel modeloM = new DefaultTableModel();
            modeloM.addColumn("N°");
            modeloM.addColumn("Periodo");
            modeloM.addColumn("Inicio");
            modeloM.addColumn("Fecha");
            modeloM.addColumn("Turno");
            modeloM.addColumn("C-A");
            modeloM.addColumn("Alumno");
            modeloM.addColumn("Curso");
            modeloM.addColumn("Tipo");
            modeloM.addColumn("Docente");
            jtableMatriculasAll.setModel(modeloM);

          // Ajustar el ancho de las columnas
          jtableMatriculasAll.getColumnModel().getColumn(0).setPreferredWidth(8); // Numero Matricula
          jtableMatriculasAll.getColumnModel().getColumn(1).setPreferredWidth(35); // Periodo
          jtableMatriculasAll.getColumnModel().getColumn(2).setPreferredWidth(30); // Mes Inicio
          jtableMatriculasAll.getColumnModel().getColumn(3).setPreferredWidth(35); // Fecha
          jtableMatriculasAll.getColumnModel().getColumn(4).setPreferredWidth(30); // Turno
          jtableMatriculasAll.getColumnModel().getColumn(5).setPreferredWidth(20); // cod_alumno
          jtableMatriculasAll.getColumnModel().getColumn(6).setPreferredWidth(100); // Alumno
          jtableMatriculasAll.getColumnModel().getColumn(7).setPreferredWidth(100); // Curso
          jtableMatriculasAll.getColumnModel().getColumn(8).setPreferredWidth(20); // tipo
          jtableMatriculasAll.getColumnModel().getColumn(9).setPreferredWidth(100); // Docente

          // Hacer la tabla no editable
          jtableMatriculasAll.setDefaultEditor(Object.class, null);

          while (rs.next()) {
            Object[] fila = new Object[]{
                rs.getString(1), //num_matricula
                rs.getString(2), //periodo
                rs.getString(3), //mes_inicio
                rs.getString(4), //fecha
                rs.getString(5), //turno
                rs.getString(6), //cod_alumno
                rs.getString(7), // nombre completo del alumno
                rs.getString(8), //curso
                rs.getString(9), //tipo
                rs.getString(10) // nombre completo del docente
            };
            modeloM.addRow(fila);
        }
          // Mostrar la cantidad total de registros
        lblTotalRegistros.setText("Total de registros: " + rowCount);
        } catch (SQLException ex) {
            Logger.getLogger(jfrmMatricula.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmVerMatriculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmVerMatriculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmVerMatriculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmVerMatriculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmVerMatriculas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtableMatriculasAll;
    private javax.swing.JTextField jtxtBusquedaGlobal;
    private javax.swing.JLabel lblTotalRegistros;
    // End of variables declaration//GEN-END:variables
}
